### ISSUE TITLE
Addon signature

### ISSUE THREAD

**Issue by Max-Pare** [MagicJinn/Block-Sponsor-Comments#2]
Will a signed .xpi file for this addon be provided so it can be installed on Firefox non-developer edition?
I got it signed for myself so I can just install as any other addon.

**Comment by MagicJinn** [comment]
The addon is in the [Firefox Addon Store](https://addons.mozilla.org/en-US/firefox/addon/block-sponsor-comments), so it would be best to get your xpi from there if you need it. If I were to wait until Firefox and Chrome sign it, it could take several days for each release to appear on the Releases page, which is the exact opposite of why I provide releases there, for people to start using the extension before it is signed.
