### ISSUE TITLE
New sponsor at: [TF2] Cheating in MvM - The Case Continues

### ISSUE THREAD

**Issue by moosetwin0** [MagicJinn/Block-Sponsor-Comments#22]
URL: https://www.youtube.com/watch?v=VsTYx9GCA8E

Note: I can't add the New Sponsor label, you will either need to add it yourself or allow people making submissions to assign them to their own issues.

**Comment by MagicJinn** [comment]
Ah, didn't know labels were locked down like that. Will have a look. Thanks for reporting!
