### ISSUE TITLE
New sponsor: POURQUOI Certains Pays Conduisent à DROITE et d'autres à GAUCHE ?

### ISSUE THREAD

**Issue by gut1414** [MagicJinn/Block-Sponsor-Comments#56]
URL: https://youtube.com/watch?v=h6u29G4KDCY

Notes:
Presence of theses sponsored words: "👉 Comparez les meilleures offres d'assurance auto, avec notre comparateur gratuit : https://forms.lecomparateurassurance....", 

The link redirect to "https://forms.lecomparateurassurance.com/", a sponsorship.

**Comment by MagicJinn** [comment]
Thanks for the report! Also big thanks on pointing out the specific sponsor, my French is very bad :)
