### ISSUE TITLE
New sponsor: Tsar Bomba : La Bombe la plus Puissante de l'Histoire

### ISSUE THREAD

**Issue by gut1414** [MagicJinn/Block-Sponsor-Comments#81]
URL: https://youtube.com/watch?v=MWc3O9QYk10

Notes:
Sponsorship with Rosetta Stone

**Comment by MagicJinn** [comment]
Good catch!

**Comment by gut1414** [comment]
Sponsor text "Rosetta Stone" not removed, just link. Why?

**Comment by gut1414** [comment]
Thanks for your fix against link.

**Comment by MagicJinn** [comment]
Oops, looks like it didn't fully get the sponsor. I'll add Rosetta Stone to the blocked words. I'm not sure when the next update will be, I usually update between 1-2 weeks.
